FROM microsoft/aspnetcore:1
LABEL Name=lotrapi Version=0.0.1

RUN apt-get update
RUN apt-get install -y --no-install-recommends curl unzip
RUN curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

WORKDIR /app
EXPOSE 5000
ENTRYPOINT tail -f /dev/null
